### ISSUE TITLE
Buffer Object has no method 'clear'

### ISSUE THREAD

**Issue by computersarecool** [ekryski/caress-server#13]
I can get the server running, but as soon as I actually send TUIO data, I get the following error (as printed in terminal).  Thanks for any help and I am sure that this will be amazing software when I get it working. 

/Users/User/caress/node_modules/caress-server/lib/tuio-packet.js:284
  var zeroBuffer = new Buffer(1).clear();
                                 ^
TypeError: Object � has no method 'clear'
    at decodeString (/Users/User/caress/node_modules/caress-server/lib/tuio-packet.js:284:34)
    at decode (/Users/User/caress/node_modules/caress-server/lib/tuio-packet.js:213:17)
    at Packet.toJSON (/Users/User/caress/node_modules/caress-server/lib/tuio-packet.js:93:17)
    at Socket.<anonymous> (/Users/User/caress/node_modules/caress-server/lib/caress-server.js:60:57)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)

npm ERR! caress-server@0.1.1 start: `node examples/server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the caress-server@0.1.1 start script.
npm ERR! This is most likely a problem with the caress-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node examples/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls caress-server
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/User/caress/node_modules/caress-server
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/User/caress/node_modules/caress-server/npm-debug.log
npm ERR! not ok code 0

**Comment by computersarecool** [comment]
If you use npm install, as outlined on the website, in tuio-packet, 

var buffertools = require('buffertools');   does not extend, which does not give it the clear method.  This is fixed on the GitHub version. Thanks

**Comment by amosk** [comment]
After a clone you get 

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/amosk/Desktop/caress-server-github/examples/server.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I think it would be helpful to users if the install instructions included installing from GitHub. In my case I ran "npm install" from the caress-server directory. (Complements of http://expressjs.com/guide.html)

**Comment by Hellmy** [comment]
I have a similar problem as above.
Cloned the repo and made a npm install.
Is there a fast "how to" fix?

```
   info  - socket.io started

module.js:340
    throw err;
          ^
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (E:\Students\Qualifizierungsarbeiten\Manuel_Oddoy\care
ss-server\node_modules\buffertools\buffertools.js:26:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (...\caress-server\lib\tuio-packet.js:12:1)
```

when I take the files from the command `npm install caress-server` then I get the same error as in the first post

**Comment by computersarecool** [comment]
The "quick fix" would be to download from this https://github.com/ekryski/caress-server github repo

**Comment by Hellmy** [comment]
Hey,
Thank you for the fast answer.
But still there is the posted error above  when downloading the github repo.
Perhaps something wrong with the path options because `Error: Cannot find module './build/Debug/buffertools.node'` is the error message.

What I've done:
1. Clone git@github.com:ekryski/caress-server.git
2. npm install
3. npm start

What I get during npm start:

```
C:\...\caress-server>npm start

> caress-server@0.1.1 start C:\...\caress-server
> node examples/server.js

   info  - socket.io started

module.js:340
    throw err;
          ^
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\...\caress-server\node_modules\buffertool
s\buffertools.js:26:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! caress-server@0.1.1 start: `node examples/server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the caress-server@0.1.1 start script.
npm ERR! This is most likely a problem with the caress-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node examples/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls caress-server
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\...\caress-server
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\...\npm-debug.log
npm ERR! not ok code 0
```

System:
Windows 8.1

Thanks for the time, perhaps I´m just doing something wrong ;-)

**Comment by amosk** [comment]
I don't know if this matters but did you try executing with "nodejs examples/server.js" or "nodejs server.js" from the examples directory instead of "npm start"?

**Comment by Hellmy** [comment]
Hey,

thanks but no other result =/

**Comment by jBachalo** [comment]
I've tried both ways, npm start and launching directly using node server and both give me the same error as above.Something is obviously broken

Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/foo/bin/caress-server-master/node_modules/buffertools/buffertools.js:26:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
