### ISSUE TITLE
Error: Cannot find module './build/Debug/buffertools.node'

### ISSUE THREAD

**Issue by jBachalo** [ekryski/caress-server#18]
Tried launching both ways, using npm start as well as calling directlynode server.js. Same error.

Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/foo/bin/caress-server-master/node_modules/buffertools/buffertools.js:26:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by dennistimmermann** [comment]
I've resolved this issue by building the debug version of buffertools.
`cd` into `caress-server/node_modules/buffertools` and run `node-gyp rebuild -d`. This fixed it for me

**Comment by shangzz** [comment]
I did this, but failed. See below for details:
D:\TUIO\caress-server-master\node_modules\buffertools>node-gyp rebuild -d
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@4.4.3 | win32 | ia32
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_mod
ules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\TUIO\\caress-server-master\\node_modules\\buffertools
\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_mod
ules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\4.4.3\\include\\node
\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\4.4.
3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming
\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\TUIO\\caress-server-master\\node_mo
dules\\buffertools',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\TUIO\\caress-server-master\\node_modules\\buffertools
\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Debug;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_
load_hook.cc(34): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认
 int [D:\TUIO\car
ess-server-master\node_modules\buffertools\build\binding.sln]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_
load_hook.cc(34): error C2440: “初始化”: 无法从“PfnDliHook”转换为“int” [D:
\TUIO\caress-s
erver-master\node_modules\buffertools\build\binding.sln]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_
load_hook.cc(34): error C2146: 语法错误 : 缺少“;”(在标识符“__pfnDliNotifyHook
2”的前面) [D:\T
UIO\caress-server-master\node_modules\buffertools\build\binding.sln]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_
load_hook.cc(34): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认
 int [D:\TUIO\car
ess-server-master\node_modules\buffertools\build\binding.sln]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_
load_hook.cc(34): error C2373: “__pfnDliNotifyHook2”: 重定义；不同的类型修饰符
 [D:\TUIO\car
ess-server-master\node_modules\buffertools\build\binding.sln]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_
load_hook.cc(34): error C2440: “初始化”: 无法从“FARPROC (__stdcall *)(unsigne
d int,De
layLoadInfo *)”转换为“int” [D:\TUIO\caress-server-master\node_modules\buffert
ools\
build\binding.sln]
d:\tuio\caress-server-master\node_modules\buffertools\BoyerMoore.h(5): fatal er
ror C1083: 无法打开包括文件:“stdint.h”: No such file or directory [D:\TUIO\car
ess-serve
r-master\node_modules\buffertools\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Adminis
trator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d" "-d"
gyp ERR! cwd D:\TUIO\caress-server-master\node_modules\buffertools
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
