### ISSUE TITLE
server.js won't set up

### ISSUE THREAD

**Issue by moebiusfrost** [ekryski/caress-server#19]
I can's start up the server.js after I installed caress-server with 

Ducs-MacBook-Pro:caress-server Ian$ node examples/server.js
/Users/Ian/node_modules/caress-server/examples/server.js:16
io.enable("browser client minification");
   ^

TypeError: io.enable is not a function
    at Object.<anonymous> (/Users/Ian/node_modules/caress-server/examples/server.js:16:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

is it something with caress-server, or with socket.io?

**Comment by moebiusfrost** [comment]
Problem solved. I had to update npm

**Comment by ekryski** [comment]
good to know! Thanks.
